import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // Stitch design system — PICO Cloud
        primary: '#004ac6',
        'on-primary': '#ffffff',
        'primary-container': '#2563eb',
        'on-primary-container': '#eeefff',
        'primary-fixed': '#dbe1ff',
        'primary-fixed-dim': '#b4c5ff',
        'on-primary-fixed': '#00174b',
        'on-primary-fixed-variant': '#003ea8',
        secondary: '#0058be',
        'secondary-container': '#2170e4',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#fefcff',
        'secondary-fixed': '#d8e2ff',
        'secondary-fixed-dim': '#adc6ff',
        'on-secondary-fixed': '#001a42',
        'on-secondary-fixed-variant': '#004395',
        tertiary: '#943700',
        'tertiary-container': '#bc4800',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffede6',
        'tertiary-fixed': '#ffdbcd',
        'tertiary-fixed-dim': '#ffb596',
        'on-tertiary-fixed': '#360f00',
        'on-tertiary-fixed-variant': '#7d2d00',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#f7f9fb',
        'on-background': '#191c1e',
        surface: '#f7f9fb',
        'on-surface': '#191c1e',
        'on-surface-variant': '#434655',
        'surface-bright': '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'surface-dim': '#d8dadc',
        'surface-variant': '#e0e3e5',
        'surface-tint': '#0053db',
        outline: '#737686',
        'outline-variant': '#c3c6d7',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'inverse-primary': '#b4c5ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['var(--font-mono)', 'JetBrains Mono', 'monospace'],
        // Old tokens (kept for backward compat during sweep)
        'body-md': ['var(--font-inter)', 'Inter', 'system-ui', 'sans-serif'],
        'body-sm': ['var(--font-inter)', 'Inter', 'system-ui', 'sans-serif'],
        'body-lg': ['var(--font-inter)', 'Inter', 'system-ui', 'sans-serif'],
        'headline-sm': ['var(--font-inter)', 'Inter', 'system-ui', 'sans-serif'],
        'headline-md': ['var(--font-inter)', 'Inter', 'system-ui', 'sans-serif'],
        'display-lg': ['var(--font-inter)', 'Inter', 'system-ui', 'sans-serif'],
        'label-caps': ['var(--font-inter)', 'Inter', 'system-ui', 'sans-serif'],
        'code-md': ['var(--font-mono)', 'JetBrains Mono', 'monospace'],
        // New Stitch tokens
        'display-title': ['var(--font-inter)', 'Inter', 'system-ui', 'sans-serif'],
        'section-title': ['var(--font-inter)', 'Inter', 'system-ui', 'sans-serif'],
        'code-inline': ['var(--font-mono)', 'JetBrains Mono', 'monospace'],
        'body-base': ['var(--font-inter)', 'Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        // Old tokens (kept for backward compat)
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'code-md': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        // Updated tokens
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        // New Stitch tokens
        'display-title': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'section-title': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'code-inline': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'body-base': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
      spacing: {
        // Existing tokens
        'ui-sm': '0.75rem',
        'ui-md': '1rem',
        'ui-lg': '1.5rem',
        'layout-xl': '2.5rem',
        'layout-2xl': '4rem',
        'data-tight': '0.25rem',
        'data-base': '0.5rem',
        'grid-gutter': '24px',
        'section-gap': '32px',
        // New Stitch tokens
        'container-padding': '24px',
        'element-gap': '16px',
        'base': '4px',
      },
      boxShadow: {
        card: '0 1px 3px rgba(0, 0, 0, 0.05)',
        elevated: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
      },
    },
  },
  plugins: [],
};

export default config;
